# Generated by Django 5.0.7 on 2025-08-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('line_id', models.CharField(max_length=64)),
                ('station_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='vision', max_length=32)),
                ('reason', models.CharField(max_length=64)),
                ('detail', models.CharField(blank=True, max_length=128)),
                ('duration_s', models.FloatField(default=0.0)),
                ('severity', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='oee_analyti_ts_6f9163_idx'), models.Index(fields=['line_id', 'station_id'], name='oee_analyti_line_id_19d0df_idx')],
            },
        ),
    ]
