# Generated by Django 5.0.7 on 2025-08-12 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('shift_start', models.DateTimeField(db_index=True)),
                ('line_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('availability', models.FloatField(default=0.0)),
                ('performance', models.FloatField(default=0.0)),
                ('quality', models.FloatField(default=0.0)),
                ('oee', models.FloatField(default=0.0)),
                ('target_count', models.IntegerField(default=0)),
                ('actual_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('reject_count', models.IntegerField(default=0)),
                ('total_downtime_minutes', models.FloatField(default=0.0)),
                ('planned_downtime_minutes', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'line_id'], name='oee_analyti_timesta_6132f7_idx'), models.Index(fields=['shift_start', 'line_id'], name='oee_analyti_shift_s_4d94ef_idx')],
            },
        ),
    ]
