# Generated by Django 5.0.7 on 2025-09-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_analytics', '0002_productionmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLFeatureStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('line_id', models.CharField(db_index=True, max_length=50)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('feature_value', models.FloatField()),
                ('feature_type', models.CharField(choices=[('realtime', 'Real-time'), ('aggregated', 'Aggregated'), ('derived', 'Derived')], max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'line_id', 'feature_name'], name='oee_analyti_timesta_c931a7_idx'), models.Index(fields=['line_id', 'feature_name', 'timestamp'], name='oee_analyti_line_id_addb74_idx')],
                'unique_together': {('timestamp', 'line_id', 'feature_name')},
            },
        ),
        migrations.CreateModel(
            name='MLInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('line_id', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('prediction_type', models.CharField(choices=[('risk_score', 'Risk Score'), ('downtime_probability', 'Downtime Probability'), ('quality_prediction', 'Quality Prediction'), ('oee_forecast', 'OEE Forecast'), ('anomaly_score', 'Anomaly Score')], max_length=50)),
                ('prediction_value', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('explanation_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'line_id', 'model_name'], name='oee_analyti_timesta_b888b4_idx'), models.Index(fields=['line_id', 'prediction_type', 'timestamp'], name='oee_analyti_line_id_7e44c4_idx'), models.Index(fields=['model_name', 'timestamp'], name='oee_analyti_model_n_b5446c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('model_version', models.CharField(max_length=20)),
                ('model_path', models.CharField(max_length=500)),
                ('model_type', models.CharField(choices=[('downtime_prediction', 'Downtime Prediction'), ('quality_risk', 'Quality Risk'), ('oee_forecast', 'OEE Forecast'), ('anomaly_detection', 'Anomaly Detection'), ('operator_efficiency', 'Operator Efficiency')], max_length=50)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='oee_analyti_model_t_dc5031_idx'), models.Index(fields=['model_name', 'is_active'], name='oee_analyti_model_n_c19168_idx')],
            },
        ),
    ]
