# Generated by Django 5.0.7 on 2025-10-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee_analytics', '0005_mes_integration_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRangeConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(db_index=True, max_length=50)),
                ('signal_type', models.CharField(db_index=True, max_length=50)),
                ('min_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('max_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=20)),
                ('violation_action', models.CharField(
                    choices=[
                        ('ALERT', 'Alert only'),
                        ('REJECT', 'Reject data'),
                        ('FLAG', 'Flag for review')
                    ],
                    default='ALERT',
                    max_length=20
                )),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SensorRangeConfigs',
            },
        ),
        migrations.AddIndex(
            model_name='sensorrangeconfig',
            index=models.Index(
                fields=['machine_id', 'signal_type', 'is_active'],
                name='SensorRange_machine_4a9d87_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='sensorrangeconfig',
            unique_together={('machine_id', 'signal_type')},
        ),
    ]
