---
# Python role - install Python and OEE dependencies

- name: Add deadsnakes PPA for Python 3.11 (Ubuntu)
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Python 3.11
  package:
    name:
      - python3.11
      - python3.11-venv
      - python3.11-dev
      - python3-pip
    state: present

- name: Create Python virtual environment
  command: python3.11 -m venv {{ edge_install_dir }}/venv
  args:
    creates: "{{ edge_install_dir }}/venv/bin/python"
  become_user: "{{ edge_user }}"

- name: Upgrade pip in virtual environment
  pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    virtualenv: "{{ edge_install_dir }}/venv"
  become_user: "{{ edge_user }}"

- name: Install OEE Edge Gateway Python dependencies
  pip:
    name:
      - paho-mqtt==1.6.1
      - asyncua==1.0.4
      - pycomm3==1.2.9  # Allen-Bradley
      - python-snap7==1.3  # Siemens
      - redis==5.0.1
      - rocksdict==0.3.20
      - prometheus-client==0.19.0
      - pyyaml==6.0.1
      - aiohttp==3.9.1
      - tahu-protobuf==1.0.0  # Sparkplug B
    state: present
    virtualenv: "{{ edge_install_dir }}/venv"
  become_user: "{{ edge_user }}"
