version: '3.8'

services:
  # Loki - Log aggregation system
  loki:
    image: grafana/loki:2.9.3
    container_name: oee_loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - mqtt_cluster
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Promtail - Log collection agent
  promtail:
    image: grafana/promtail:2.9.3
    container_name: oee_promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - promtail_positions:/tmp
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - mqtt_cluster
    depends_on:
      - loki
    restart: unless-stopped

networks:
  mqtt_cluster:
    name: compose_mqtt_cluster
    external: true

volumes:
  loki_data:
    driver: local
  promtail_positions:
    driver: local
